Pages/C_info.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication3.Pages.Models;
using WebApplication6.Pages;

namespace WebApplication3.Pages
{
    public class C_infoModel : PageModel
    {
        private readonly ILogger<C_infoModel> _logger;

        public Companyinfo company { get; set; }
        public WebApplication3.Pages.Models.DB Db { get; set; }
        public C_infoModel(ILogger<C_infoModel> logger, WebApplication3.Pages.Models.DB db)
        {
            _logger = logger;
            Db = db;
        }
        public IActionResult OnGet()
        {
            company = Db.getCompanyInfo();
            if ((HttpContext.Session.GetInt32("ID")) == 0 || (HttpContext.Session.GetInt32("ID")) == null)
            {
                return RedirectToPage("/index");
            }
            else
            {
                if((HttpContext.Session.GetInt32("DID")) == 50101 )
                {
                    return Page();
                }
                else
                {
                    return RedirectToPage("/index");
                }
            }
        }

    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebApplication3.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Pages/Formrequest.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication3.Pages
{
    public class FormrequestModel : PageModel
    {
        private readonly ILogger<FormrequestModel> _logger;
        public FormrequestModel(ILogger<FormrequestModel> logger, WebApplication3.Pages.Models.DB db)
        {
            _logger = logger;
            Db = db;
        }
        public WebApplication3.Pages.Models.DB Db { get; set; }

        [BindProperty(SupportsGet = true)]
        public string LeaveReason { get; set; }

        [BindProperty(SupportsGet = true)]
        public DateOnly StartDate { get; set; }

        [BindProperty(SupportsGet = true)]
        public DateOnly EndDate { get; set; }
        public IActionResult OnGet()
        {
            if ((HttpContext.Session.GetInt32("ID")) == 0 || (HttpContext.Session.GetInt32("ID")) == null)
            {
                return RedirectToPage("/index");
            }
            else
            {
                if ((HttpContext.Session.GetInt32("DID")) != 50101)
                {
                    return Page();
                }
                else
                {
                    return RedirectToPage("/index");
                }
            }
        }

        public IActionResult OnPostSubmitLeaveRequest()
        {
            Db.SendDayoffReq((int)HttpContext.Session.GetInt32("ID"), LeaveReason, StartDate, EndDate);
            return RedirectToPage("/PersonalInfo2");
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.IdentityModel.Tokens;
using System.Data;
using System.Reflection;
using WebApplication3.Pages.Models;

namespace WebApplication3.Pages
{
    public class IndexModel : PageModel
    {
        public DataTable Dt { get; set; }
        public DataTable Dt2 { get; set; }
        public Companyinfo company { get; set; }
        public DataTable Dt3 { get; set; }
        public DataTable products { get; set; }



        private readonly ILogger<IndexModel> _logger;
        
        public WebApplication3.Pages.Models.DB Db { get; set; }


        [BindProperty(SupportsGet = true)]
        public Models.User USER1 { get; set; }
        public IndexModel(ILogger<IndexModel> logger, Models.DB db)
        {
            _logger = logger;
            Db = db;
        }

        public void OnGet()
        {
            company = Db.getCompanyInfo();
            Dt = Db.offers();
            Dt2 = Db.offers2();
            Dt3 = Db.offers3();
            products=Db.getProducts();
            if ((HttpContext.Session.GetInt32("ID")) != 0 && (HttpContext.Session.GetInt32("ID")) != null)
            {
                USER1.ID = (int)HttpContext.Session.GetInt32("ID");
            }

        }

        public IActionResult OnPostLogin()
        {
            return RedirectToPage("/LogIn2");
        }

        public IActionResult OnPostLogout()
        {
            HttpContext.Session.SetInt32("ID", 0);

            return RedirectToPage("/index");
        }
    }
}

Pages/Jobs.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication3.Pages
{
    public class JobsModel : PageModel
    {
        public IActionResult OnGet()
        {
            if ((HttpContext.Session.GetInt32("ID")) == 0 || (HttpContext.Session.GetInt32("ID")) == null)
            {
                return RedirectToPage("/index");
            }
            else
            {
                if ((HttpContext.Session.GetInt32("DID")) == 50101)
                {
                    return Page();
                }
                else
                {
                    return RedirectToPage("/index");
                }
            }
        }
    }
}

Pages/LogIn2.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using WebApplication3.Pages.Models;

namespace WebApplication3.Pages
{
    public class Index1Model : PageModel
    {
        private readonly ILogger<Index1Model> _logger;
        public Index1Model(ILogger<Index1Model> logger, WebApplication3.Pages.Models.DB db)
        {
            _logger = logger;
            Db = db;
        }
        public WebApplication3.Pages.Models.DB Db { get; set; }

        [BindProperty(SupportsGet = true)]
        public Models.User USER2 { get; set; }
        public IActionResult OnGet()
        {
            if ((HttpContext.Session.GetInt32("ID"))!= 0 && (HttpContext.Session.GetInt32("ID")) != null)
            {
                return RedirectToPage("/index");
            }
            else
            {
                return Page();
            }
        }
        public IActionResult OnPost()
        {
            //if (!ModelState.IsValid)
            //{
            //    return Page();
            //}

            USER2 = Db.getEmpInfo(USER2.ID);

            if (USER2 != null)
            {
                HttpContext.Session.SetInt32("ID", USER2.ID);
                HttpContext.Session.SetInt32("DID", USER2.DID);
                return RedirectToPage("/index", new { USER1 = this.USER2 });
            }
            else
            {
                return Page();
            }
        }

    }
}

Pages/PersonalInfo2.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Net;
using System.Numerics;
using System.Runtime.Intrinsics.X86;
using WebApplication3.Pages.Models;

namespace WebApplication3.Pages
{
    public class EmployeeInfoModel : PageModel
    {
        private readonly ILogger<EmployeeInfoModel> _logger;
        public EmployeeInfoModel(ILogger<EmployeeInfoModel> logger, WebApplication3.Pages.Models.DB db)
        {
            _logger = logger;
            Db = db;
        }
        public WebApplication3.Pages.Models.DB Db { get; set; }

        [BindProperty(SupportsGet = true)]
        public Models.User USER2 { get; set; }

        // OnGet method to initialize employee data
        public IActionResult OnGet()
        {
            if ((HttpContext.Session.GetInt32("ID")) == 0 || (HttpContext.Session.GetInt32("ID")) == null)
            {
                return RedirectToPage("/index");
            }
            else
            {
                USER2 = Db.getEmpInfo((int)HttpContext.Session.GetInt32("ID"));
                return Page();
            }
        }


        public IActionResult OnPostSaveFirstName(string firstName)
        {
            // Check if Employee is null (it should not be in this context, but it's a good safety check)
            USER2 = Db.EditEmpFname(firstName, (int)HttpContext.Session.GetInt32("ID"));
            return RedirectToPage();
        }



        public IActionResult OnPostSaveLastName(string lastName)
        {
            USER2 = Db.EditEmpLname(lastName, (int)HttpContext.Session.GetInt32("ID"));
            return RedirectToPage();
        }


        public IActionResult OnPostSavePhone(string phone)
        {
            USER2 = Db.EditEmpPhone(phone, (int)HttpContext.Session.GetInt32("ID"));
            return RedirectToPage();
        }

        public IActionResult OnPostSaveAddress(string address)
        {
            USER2 = Db.EditEmpAddress(address, (int)HttpContext.Session.GetInt32("ID"));
            return RedirectToPage();
        }

        public IActionResult OnPostSaveEmail(string email)
        {
            USER2 = Db.EditEmpEmail(email, (int)HttpContext.Session.GetInt32("ID"));
            return RedirectToPage();
        }

        public IActionResult OnPostReqDay()
        {
            return RedirectToPage("/Formrequest");
        }
    }

    // Employee class to hold employee data
}

Pages/Stat.cshtml.cs
using ChartExample.Models.Chart;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System;
using System.Data;


namespace WebApplication3.Pages
{
    public class StatModel : PageModel
    {
        public Models.DB db { get; set; }
        [BindProperty]
        public DataTable Name { get; set; }
       
        [BindProperty]
        public int RangeStart { get; set; }
        [BindProperty]
        public int Range { get; set; }
        public DataTable product { get; set; }

        public DataTable dt { get; set; }
        public DataTable chart1 { get; set; }

        public ChartJs BarChart { get; set; }
        public ChartJs PieChart { get; set; }
        public string ChartJson { get; set; }
        public string ChartJson1 { get; set; }
        public StatModel()
        {
            db = new Models.DB(); // Initialize db
            BarChart = new ChartJs();
            PieChart = new ChartJs();
        }
        public void OnGet()
        {
            Name = db.mostcomapny();
            Console.WriteLine(RangeStart);
            product = db.mostpaidproduct();
            dt = db.mostysalesagent();
            chart1 = db.inbetweenamount(RangeStart);
            RangeStart = Convert.ToInt32( HttpContext.Session.GetInt32("range"));
            Range = Convert.ToInt32(HttpContext.Session.GetInt32("range2"));

            Dictionary<string, int> productamount = db.productamount(RangeStart);
            Dictionary<string, int> finamount = db.finchart(Range);
            setUpBarChart(productamount);
            setUpPieChart(finamount);

            //if ((HttpContext.Session.GetInt32("ID")) == 0 || (HttpContext.Session.GetInt32("ID")) == null)
            //{
            //    return RedirectToPage("/index");
            //}
            //else
            //{
            //    if ((HttpContext.Session.GetInt32("DID")) == 50101)
            //    {
            //        return Page();
            //    }
            //    else
            //    {
            //        return RedirectToPage("/index");
            //    }


            //}
        }
        private void setUpBarChart(Dictionary<string, int> dataToDisplay)
        {
            try
            {
                // 1. set up chart options 
                BarChart.type = "bar";
                BarChart.options.responsive = true;
               
            // 2. separate the received Dictionary data into labels and data
            var labelsArray = new List<string>();
                var dataArray = new List<double>();
                foreach (var data in dataToDisplay)
                {
                    labelsArray.Add(data.Key);
                    dataArray.Add(data.Value);
                }
                BarChart.data.labels = labelsArray;
                // 3. set up a dataset 
                var firsDataset = new Dataset();
                firsDataset.label = " ";
                firsDataset.data = dataArray.ToArray();
                BarChart.data.datasets.Add(firsDataset);
                // 4. finally, convert the object to json to be able to inject in 
                ChartJson = JsonConvert.SerializeObject(BarChart, new JsonSerializerSettings
                {
                    NullValueHandling = NullValueHandling.Ignore,
                });
            }
            catch (Exception e)
            {
                Console.WriteLine("Error initialising the bar chart inside Index.cshtml.cs"); 
                throw e;
            }

        }
        private void setUpPieChart(Dictionary<string, int> dataToDisplay)
        {
            try
            {
                // Ensure PieChart is properly instantiated
                if (PieChart == null)
                    PieChart = new ChartJs();

                // Ensure PieChart.data is properly instantiated
                if (PieChart.data == null)
                    PieChart.data = new Data();

                // Ensure labels and datasets are properly instantiated
                if (PieChart.data.labels == null)
                    PieChart.data.labels = new List<string>();
                if (PieChart.data.datasets == null)
                    PieChart.data.datasets = new List<Dataset>();

                // 1. Set up chart options
                PieChart.type = "pie";
                PieChart.options.responsive = true;

                // 2. Separate the received Dictionary data into labels and data
                var labelsArray = new List<string>();
                var dataArray = new List<double>();
                foreach (var data in dataToDisplay)
                {
                    labelsArray.Add(data.Key);
                    dataArray.Add(data.Value);
                }

                // Clear and populate PieChart.data.labels
                PieChart.data.labels.Clear();
                PieChart.data.labels.AddRange(labelsArray);

                // 3. Set up a dataset
                var firstDataset = new Dataset();
                firstDataset.label = " ";
                firstDataset.data = dataArray.ToArray();
                firstDataset.backgroundColor = GenerateRandomColors(dataArray.Count).ToArray();

                PieChart.data.datasets.Clear();
                PieChart.data.datasets.Add(firstDataset);

                // 4. Convert the object to JSON to inject into the front end
                ChartJson1 = JsonConvert.SerializeObject(PieChart, new JsonSerializerSettings
                {
                    NullValueHandling = NullValueHandling.Ignore,
                });
            }
            catch (Exception e)
            {
                Console.WriteLine("Error initializing the pie chart inside Index.cshtml.cs");
                throw e;
            }
        }



        private List<string> GenerateRandomColors(int count)
        {
            var colors = new List<string>();
            var random = new Random();

            for (int i = 0; i < count; i++)
            {
                var color = $"rgb({random.Next(256)}, {random.Next(256)}, {random.Next(256)})";
                colors.Add(color);
            }

            return colors;
        }




        public IActionResult  OnPostRange()
        {
            HttpContext.Session.SetInt32("range", RangeStart);
            Console.WriteLine(RangeStart);
            Console.WriteLine(Range);
            return RedirectToPage("/Stat");
            
        }

        public IActionResult OnPostFin()
        {
            HttpContext.Session.SetInt32("range2", Range);
            Console.WriteLine(Range);
            return RedirectToPage("/Stat");

        }

    }
}

Pages/Jobs.cshtml
@page
@model WebApplication3.Pages.JobsModel
@{
}

Pages/Stat.cshtml
@page
@model WebApplication3.Pages.StatModel
@{
}

<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>صفحة الإحصائيات </title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS for baby blue theme -->
    <style>
         body {
            background-color: #eef2f3; /* Light baby blue background */
        }

        .card {
            background-color: #e6f7ff; /* Soft baby blue for cards */
            border: 1px solid #0d47a1;
        }

        .card-header {
            background-color: #0d47a1; /* Lighter baby blue header */
            color: #e6f7ff; /* Darker blue text */
        }

        .card-footer {
            background-color: #eef2f3; /* Very light blue footer */
        }

        .stat-value {
            font-size: 2rem;
            font-weight: bold;
        }

        .stat-label {
            color: #0277bd;
        }

        .section-title {
            color: #01579b;
        }

        .sidenav {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            right: 0;
            background-color: #111;
            overflow-x: hidden;
            transition: 0.5s;
            padding-top: 60px;
        }

            .sidenav a {
                padding: 8px 8px 8px 32px;
                text-decoration: none;
                font-size: 25px;
                color: #818181;
                display: block;
                transition: 0.3s;
            }

                .sidenav a:hover {
                    color: #f1f1f1;
                }

            .sidenav .closebtn {
                position: absolute;
                top: 0;
                right: 25px;
                font-size: 36px;
                margin-right: 50px;
            }

        .toggle_icon {
            cursor: pointer;
        }

            .toggle_icon img {
                width: 30px;
            }
    </style>
    <!-- Chart.js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <div class="header_section">
        <div class="container">
            <div class="containt_main">
                @if (HttpContext.Session.GetInt32("ID") == 0 || HttpContext.Session.GetInt32("ID") == null)
                {
                    <div id="mySidenav" class="sidenav">
                        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                        <a href="/index">الصفحة الرئيسية</a>
                    </div>
                    <span class="toggle_icon" onclick="openNav()"><img src="images/toggle-icon.png"></span>
                }
                else
                {
                    if (HttpContext.Session.GetInt32("DID") == 50101)
                    {
                        <div id="mySidenav" class="sidenav">
                            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                            <a href="/index">الصفحة الرئيسية</a>
                            <a asp-page="/Personalinfo2">المعلومات الشخصية</a>
                            <a href="/Stat">الاحصائيات</a>
                            <a href="/transactions">العمليات</a>
                            <a href="/C_info">معلومات الشركة</a>
                            <a href="/employee">الموظفين</a>
                            <a href="/product">الادوية</a>
                            <a href="/requestdayoff">ايام الاجازة</a>
                            <a href="/fin">المعلومات المالية</a>
                        </div>
                    }
                    else if (HttpContext.Session.GetInt32("DID") == 5111)
                    {
                        <div id="mySidenav" class="sidenav">
                            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                            <a href="/index">الصفحة الرئيسية</a>
                            <a asp-page="/Personalinfo2">المعلومات الشخصية</a>
                            <a href="/transactions">العمليات</a>
                        </div>
                    }
                    else if (HttpContext.Session.GetInt32("DID") == 50106)
                    {
                        <div id="mySidenav" class="sidenav">
                            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                            <a href="/index">الصفحة الرئيسية</a>
                            <a asp-page="/Personalinfo2">المعلومات الشخصية</a>
                            <a href="/fin">المعلومات المالية</a>
                        </div>
                    }
                    else if (HttpContext.Session.GetInt32("DID") == 50102)
                    {
                        <div id="mySidenav" class="sidenav">
                            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                            <a href="/index">الصفحة الرئيسية</a>
                            <a asp-page="/Personalinfo2">المعلومات الشخصية</a>
                            <a href="/transactions">العمليات</a>
                        </div>
                    }
                    else if (HttpContext.Session.GetInt32("DID") == 50108)
                    {
                        <div id="mySidenav" class="sidenav">
                            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                            <a href="/index">الصفحة الرئيسية</a>
                            <a asp-page="/Personalinfo2">المعلومات الشخصية</a>
                            <a href="/product">الادوية</a>
                        </div>
                    }
                    <span class="toggle_icon" onclick="openNav()"><img src="images/toggle-icon.png"></span>
                }
            </div>
        </div>
    </div>

    <div class="container mt-5">
        <div class="row">
            <!-- Stats Overview -->
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">اكثر المنتجات بيعا</h5>
                    </div>
                    <div class="card-body">
                        @if (Model.product != null && Model.product.Rows.Count > 0)
                        {
                            @foreach (System.Data.DataRow row in Model.product.Rows)
                            {
                                <p>
                                    <strong style="font-size: 1.5em;">@row["pname"]</strong>
                                </p>
                                <div style="display: inline;">
                                    <span>@row["c"]</span>
                                    <span>عملية</span>
                                </div>
                            }
                        }
                        
                        
                    </div>
                    
                </div>
            </div>
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">اكثر الشركات تعاملا</h5>
                    </div>
                    @if (Model.Name != null && Model.Name.Rows.Count > 0)
                    {
                        @foreach (System.Data.DataRow row in Model.Name.Rows)
                        {
                            <p>
                                <strong style="font-size: 1.5em;">@row["cname"]</strong>
                            </p>
                            <div style="display: inline;">
                                <span>@row["c"]</span>
                                <span>عملية</span>
                            </div>
                        }
                    }

                </div>
            </div>
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">اكثر المندوبين ابراما للصفقات</h5>
                    </div>
                    <div class="card-body">
                        
                        @if (Model.dt != null && Model.dt.Rows.Count > 0)
                        {
                            @foreach (System.Data.DataRow row in Model.dt.Rows)
                            {
                               
                                <div>
                                <p style="display: inline; font-size: 1.5em; font-weight: bold;">
                                    @($"{@row["FName"]} {@row["LName"]}")
                                </p>
                                <span style="margin-left: 10px;">@row["c"]</span>
                                <span>عملية</span>
                                </div>

                            }
                        }

                    </div>
                  
                </div>
            </div>
        </div>

        <!-- Detailed Stats Section -->
        
        <div class="container mt-4">
    <form method="post">
        <label for="rangeStart">الحد الاعلي:</label>
        <div class="d-flex">
            <!-- Dropdown for Range Start -->
            <select id="rangeStart" class="form-select w-25" asp-for="RangeStart">
                <option value="100" >100</option>
                <option value="200" >200</option>
                <option value="300" >300</option>
                <option value="400" >400</option>
                <option value="500" >500</option>
                <option value="600" >600</option>
                <option value="700" >700</option>
                <option value="800" >800</option>
                <option value="900" >900</option>
                <option value="1000">1000</option>
            </select>

            <!-- Input for custom Range Start with validation for positive numbers -->
            <input type="number" id="customRangeStart" class="form-control ms-2 w-25" placeholder="اختر" min="0" asp-for="RangeStart"  />
        </div>
        <button type="submit" asp-page-handler="range" class="btn btn-primary mt-3">نفذ</button>
    </form>
</div>
        <div class="container mt-4">
            <form method="post">
                <label for="rangeStart">الحالة:</label>
                <div class="d-flex">
                    <!-- Dropdown for Range Start -->
                    <select id="rangeStart" class="form-select w-25" asp-for="Range">
                        <option value="0">دين</option>
                        <option value="1">ائتمان</option>
                        
                    </select>

                    <!-- Input for custom Range Start with validation for positive numbers -->
                    
                </div>
                <button type="submit" asp-page-handler="fin" class="btn btn-primary mt-3">نفذ</button>
            </form>
        </div>



        <!-- Charts Section -->
        <div class="row mt-5">
            <!-- Bar Chart for Visitors & Views -->
            <div class="col-md-6 mb-4">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">إجمالي المنتجات والكميات</h5>
                    </div>
                    <div class="card-body">
                        <div class="chart-container" width="200" height="200">
                            <canvas id="barChart"></canvas>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Pie Chart for Bounce Rate & Conversion Rate -->
            <div class="col-md-6 mb-4">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">معدل الارتداد ومعدل التحويل</h5>
                    </div>
                    <div class="card-body">
                        <div class="chart-container" width="200" height="200">
                            <canvas id="PieChart"></canvas>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  

    <!-- Bootstrap JS and dependencies (optional for interactivity) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>


   
    <script type="module">
        document.addEventListener('DOMContentLoaded', (event) => {
            var ctx = document.getElementById('barChart');
            var myChart = new Chart(ctx, @Html.Raw(Model.ChartJson) );
        });

        document.addEventListener('DOMContentLoaded', (event) => {
            var ctx2 = document.getElementById('PieChart');
            var myChart2 = new Chart(ctx2, @Html.Raw(Model.ChartJson1) );
        });
    </script>
    

</body>
</html>